package transactionworkshopentities

import "time"

const TableNameWorkOrder = "trx_work_order"

type WorkOrder struct {
	WorkOrderSystemNumber              int       `gorm:"column:work_order_system_number;size:30;primaryKey" json:"work_order_system_number"`
	CompanyID                          int       `gorm:"column:company_id;size:30;" json:"company_id"`
	WorkOrderDocumentNumber            string    `gorm:"column:work_order_document_number;size:50;" json:"work_order_document_number"`
	WorkOrderStatusID                  int       `gorm:"column:work_order_status_id;size:30;" json:"work_order_status_id"`
	WorkOrderDate                      time.Time `gorm:"column:work_order_date;type:datetime" json:"work_order_date"`
	WorkOrderCloseDate                 time.Time `gorm:"column:work_order_close_date;type:datetime" json:"work_order_close_date"`
	WorkOrderTypeID                    int       `gorm:"column:work_order_type_id;size:30;" json:"work_order_type_id"`
	WorkOrderRepeatedSystemNumber      int       `gorm:"column:work_order_repeated_system_number;size:30;" json:"work_order_repeated_system_number"`
	WorkOrderRepeatedDocumentNumber    string    `gorm:"column:work_order_repeated_document_number;size:50;" json:"work_order_repeated_document_number"`
	AffiliatedCompany                  int       `gorm:"column:afiliated_company;size:30;" json:"afiliated_company"`
	ProfitCenterID                     int       `gorm:"column:profit_center_id;size:30;" json:"profit_center_id"`
	BrandID                            int       `gorm:"column:brand_id;size:30;" json:"brand_id"`
	ModelID                            int       `gorm:"column:model_id;size:30;" json:"model_id"`
	VariantID                          int       `gorm:"column:variant_id;size:30;" json:"variant_id"`
	VehicleChassisNumber               string    `gorm:"column:vehicle_chassis_number;size:50;" json:"vehicle_chassis_number"`
	BillableToID                       int       `gorm:"column:billable_to_id;size:30;" json:"billable_to_id"`
	CustomerID                         int       `gorm:"column:customer_id;size:30;" json:"customer_id"`
	PayType                            string    `gorm:"column:pay_type;size:50;" json:"pay_type"`
	FromEra                            string    `gorm:"column:from_era;size:50;" json:"from_era"`
	QueueNumber                        string    `gorm:"column:queue_number;size:50;" json:"queue_number"`
	ArrivalTime                        string    `gorm:"column:arrival_time;size:50;" json:"arrival_time"`
	ServiceMileage                     string    `gorm:"column:service_mileage;size:50;" json:"service_mileage"`
	LeaveCar                           string    `gorm:"column:leave_car;size:50;" json:"leave_car"`
	Storing                            string    `gorm:"column:storing;size:50;" json:"storing"`
	EraNumber                          string    `gorm:"column:era_number;size:50;" json:"era_number"`
	EraExpiredDate                     time.Time `gorm:"column:era_expired_date;type:datetime" json:"era_expired_date"`
	Unregister                         string    `gorm:"column:unregister;size:50;" json:"unregister"`
	ContactPersonName                  string    `gorm:"column:contact_person_name;size:50;" json:"contact_person_name"`
	ContactPersonPhone                 string    `gorm:"column:contact_person_phone;size:50;" json:"contact_person_phone"`
	ContactPersonMobile                string    `gorm:"column:contact_person_mobile;size:50;" json:"contact_person_mobile"`
	ContactPersonContactVia            string    `gorm:"column:contact_person_contact_via;size:50;" json:"contact_person_contact_via"`
	ContractServiceSystemNumber        int       `gorm:"column:contract_service_system_number;size:30;" json:"contract_service_system_number"`
	AgreementGeneralRepairID           int       `gorm:"column:agrement_general_repair_id;size:30;" json:"agreement_general_repair_id"`
	AgreementBodyRepairID              int       `gorm:"column:agreement_body_repair_id;size:30;" json:"agreement_body_repair_id"`
	BookingSystemNumber                int       `gorm:"column:booking_system_number;size:30;" json:"booking_system_number"`
	EstimationSystemNumber             int       `gorm:"column:estimation_system_number;size:30;" json:"estimation_system_number"`
	PDISystemNumber                    float32   `gorm:"column:pdi_system_number" json:"pdi_system_number"`
	PDIDocumentNumber                  string    `gorm:"column:pdi_document_number;size:50;" json:"pdi_document_number"`
	PDILineNumber                      int       `gorm:"column:pdi_line_number;size:30;" json:"pdi_line_number"`
	ServiceRequestSystemNumber         int       `gorm:"column:service_request_system_number;size:30;" json:"service_request_system_number"`
	CampaignID                         int       `gorm:"column:campaign_id;size:30;" json:"campaign_id"`
	CampaignCode                       int       `gorm:"column:campaign_code;size:30;" json:"campaign_code"`
	InsurancePolicyNumber              string    `gorm:"column:insurance_policy_number;size:50;" json:"insurance_policy_number"`
	InsuranceExpiredDate               time.Time `gorm:"column:insurance_expired_date;type:datetime" json:"insurance_expired_date"`
	InsuranceClaimNumber               string    `gorm:"column:insurance_claim_number;size:50;" json:"insurance_claim_number"`
	InsurancePersonInCharge            string    `gorm:"column:insurance_person_in_charge;size:50;" json:"insurance_person_in_charge"`
	InsuranceOwnRisk                   string    `gorm:"column:insurance_own_risk;size:50;" json:"insurance_own_risk"`
	InsuranceWorkOrderNumber           string    `gorm:"column:insurance_work_order_number;size:50;" json:"insurance_work_order_number"`
	TotalPackage                       float32   `gorm:"column:total_package" json:"total_package"`
	TotalOperation                     float32   `gorm:"column:total_operation" json:"total_operation"`
	TotalPart                          float32   `gorm:"column:total_part" json:"total_part"`
	TotalOil                           float32   `gorm:"column:total_oil" json:"total_oil"`
	TotalMaterial                      float32   `gorm:"column:total_material" json:"total_material"`
	TotalConsumableMaterial            float32   `gorm:"column:total_consumable_material" json:"total_consumable_material"`
	TotalSublet                        float32   `gorm:"column:total_sublet" json:"total_sublet"`
	TotalPriceAccessories              float32   `gorm:"column:total_price_accessories" json:"total_price_accessories"`
	TotalDiscount                      float32   `gorm:"column:total_discount" json:"total_discount"`
	Total                              float32   `gorm:"column:total" json:"total"`
	TotalVAT                           float32   `gorm:"column:total_vat" json:"total_vat"`
	TotalAfterVAT                      float32   `gorm:"column:total_after_vat" json:"total_after_vat"`
	TotalPPH                           float32   `gorm:"column:total_pph" json:"total_pph"`
	DiscountRequestPercent             float32   `gorm:"column:discount_request_percent" json:"discount_request_percent"`
	DiscountRequestAmount              float32   `gorm:"column:discount_request_amount" json:"discount_request_amount"`
	TaxID                              int       `gorm:"column:tax_id;size:30;" json:"tax_id"`
	VATTaxRate                         float32   `gorm:"column:vat_tax_rate" json:"vat_tax_rate"`
	AdditionalDiscountStatusApprovalID int       `gorm:"column:additional_discount_status_approval;size:30;" json:"additional_discount_status_approval"`
	LastApprovalBy                     int       `gorm:"column:last_approval_by_id;size:30;" json:"last_approval_by_id"`
	LastApprovalDate                   time.Time `gorm:"column:last_approval_date" json:"last_approval_date"`
	Remark                             string    `gorm:"column:remark;size:50;" json:"remark"`
	Foreman                            int       `gorm:"column:foreman_id;size:30;" json:"foreman_id"`
	ProductionHead                     int       `gorm:"column:production_head_id;size:30;" json:"production_head_id"`
	EstTime                            float32   `gorm:"column:estimate_time" json:"estimate_time"`
	Notes                              string    `gorm:"column:notes;size:50;" json:"notes"`
	Suggestion                         string    `gorm:"column:suggestion;size:50;" json:"suggestion"`
	FSCouponNo                         string    `gorm:"column:fs_coupon_number;size:50;" json:"fs_coupon_number"`
	ServiceAdvisor                     int       `gorm:"column:service_advisor_id;size:30;" json:"service_advisor_id"`
	IncentiveDate                      time.Time `gorm:"column:incentive_date" json:"incentive_date"`
	WOCancelReason                     string    `gorm:"column:work_order_cancel_reason;size:50;" json:"work_order_cancel_reason"`
	InvoiceSystemNumber                int       `gorm:"column:invoice_system_number;size:30;" json:"invoice_system_number"`
	CurrencyID                         int       `gorm:"column:currency_id;size:30;" json:"currency_id"`
	ATPMWCFDocNo                       string    `gorm:"column:atpm_warranty_claim_form_document_number;size:50;" json:"atpm_warranty_claim_form_document_number"`
	ATPMWCFDate                        time.Time `gorm:"column:atpm_warranty_claim_form_date" json:"atpm_warranty_claim_form_date"`
	ATPMFSDocNo                        string    `gorm:"column:atpm_free_service_document_number;size:50;" json:"atpm_free_service_document_number"`
	ATPMFSDate                         time.Time `gorm:"column:atpm_free_service_date" json:"atpm_free_service_date"`
	TotalAfterDisc                     float32   `gorm:"column:total_after_discount" json:"total_after_discount"`
	ApprovalReqNo                      int       `gorm:"column:approval_request_number;size:30;" json:"approval_request_number"`
	JournalSysNo                       int       `gorm:"column:journal_system_number;size:30;" json:"journal_system_number"`
	ApprovalGatepassReqNo              int       `gorm:"column:approval_gatepass_request_number;size:30;" json:"approval_gatepass_request_number"`
	DPAmount                           float32   `gorm:"column:downpayment_amount" json:"downpayment_amount"`
	DPPayment                          float32   `gorm:"column:downpayment_payment" json:"downpayment_payment"`
	DPPaymentAllocated                 float32   `gorm:"column:downpayment_payment_allocated" json:"downpayment_payment_allocated"`
	DPPaymentVAT                       float32   `gorm:"column:downpayment_payment_vat" json:"downpayment_payment_vat"`
	DPAllocToInv                       float32   `gorm:"column:downpayment_payment_to_invoice" json:"downpayment_payment_to_invoice"`
	DPVATAllocToInv                    float32   `gorm:"column:downpayment_payment_vat_to_invoice" json:"downpayment_payment_vat_to_invoice"`
	JournalOverpaySysNo                int       `gorm:"column:journal_overpay_system_number;size:30;" json:"journal_overpay_system_number"`
	DPOverpay                          float32   `gorm:"column:downpayment_overpay" json:"downpayment_overpay"`
	SiteTypeId                         int       `gorm:"column:work_order_site_type_id;size:30;" json:"work_order_site_type_id"`
	CostCenterId                       int       `gorm:"column:cost_center_id;size:30;" json:"cost_center_id"`
	PromiseDate                        time.Time `gorm:"column:promise_date;type:datetime" json:"promise_date"`
	PromiseTime                        float32   `gorm:"column:promise_time" json:"promise_time"`
	CarWash                            string    `gorm:"column:car_wash;size:50;" json:"car_wash"`
	JobOnHoldReason                    string    `gorm:"column:job_on_hold_reason;size:50;" json:"job_on_hold_reason"`
	CustomerExpress                    string    `gorm:"column:customer_express;size:50;" json:"customer_express"`
	CPTitlePrefix                      string    `gorm:"column:contact_person_title_prefix;size:50;" json:"contact_person_title_prefix"`
}

func (*WorkOrder) TableName() string {
	return TableNameWorkOrder
}
